name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          ELEVENTY_ENV: production

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
          retention-days: 7
